# Generated by Django 6.0.5 on 2026-05-27 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='credits',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
    ]
